[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/contracts/"]
ffi = false
fs_persmissions = [{access = "read", path = "./img/"}]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
